storage: ./storage
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@erp/*':
    access: $all
    publish: $all
    unpublish: $all
  '**':
    access: $all
    proxy: npmjs
log: { type: stdout, format: pretty, level: warn }
